Add other godot auto-generated files to gitignore.
godotengine/godot-cpp-template pull request #54
Opened 2024-10-03 08:28 UTC by Ivorforce

Referring to how godot-cpp does it: https://github.com/godotengine/godot-cpp/blob/d47758910428242169ebe59329b449edf16036e0/.gitignore

2024-10-03 13:11 UTC, dsnopek commented on .gitignore
> +.import/
`.import/` is left over from Godot 3, we don't need that one, and it could be removed from godot-cpp as well

2024-10-05 16:57 UTC, dsnopek approved these changes
I don't think we really _need_ it, because we should already be ignoring any generated files by targeting the `gen/` directories, but it seems fine!

2024-10-05 16:58 UTC, dsnopek commented
Er, hang on, I didn't notice this was multiple commits. This'll need to be squashed to a single commit before it can be merged.

See https://docs.godotengine.org/en/latest/contributing/workflow/pr_workflow.html#the-interactive-rebase

2024-10-05 22:21 UTC, paddy-exe requested changes
@Ivorforce Please squash your commits

2024-10-05 22:25 UTC, Ivorforce commented
@paddy-exe done

2024-10-06 10:02 UTC, merged

2024-10-06 10:03 UTC, paddy-exe commented
Thanks!